---
- name: Place cod-startup file
  ansible.builtin.template:
    src: templates/cod-startup.sh.j2
    dest: "{{ ansible_user_dir }}/ditto/cod-start.sh"
    mode: "0755"
  tags: config
  when: cod_container | bool
- name: Place cod-stop file
  ansible.builtin.template:
    src: templates/cod-stop.sh.j2
    dest: "{{ ansible_user_dir }}/ditto/cod-stop.sh"
    mode: "0755"
  tags: config
  when: cod_container | bool
- name: Get COD image
  community.docker.docker_image_pull:
    name: ghcr.io/getditto/cod2:{{ cod_version }}
    platform: "{{ cod_platform }}"
  tags: docker
  when: cod_container | bool
- name: Place docker-compose.yml file
  ansible.builtin.template:
    src: templates/docker-compose.yml.j2
    dest: "{{ ansible_user_dir }}/ditto/docker-compose.yml"
    mode: "0600"
  tags: docker
  when: cod_container | bool
