---
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/ditto/{{ item }}"
    state: directory
    recurse: true
    mode: "0755"
  loop:
    - "bin"
    - "config"
    - "image"
    - "log"
  tags: config
- name: Place cod-config file
  ansible.builtin.template:
    src: templates/cod-agent_config.toml.j2
    dest: "{{ ansible_user_dir }}/ditto/config/cod_agent_config.toml"
    mode: "0600"
  tags: config
- name: Place PDL file
  ansible.builtin.copy:
    src: "{{ cod_pdl_path }}"
    dest: "{{ ansible_user_dir }}/ditto/config/cod.pdl"
    mode: "0600"
  tags: config
- name: Import container tasks
  ansible.builtin.import_tasks: container.yml
  when: cod_container | bool
- name: Import service tasks
  ansible.builtin.import_tasks: service.yml
  when: not cod_container | bool
